### ISSUE TITLE
페이저를 추가하였는데 페이저 안에 리사이클러뷰를 넣고 싶을때에는?

### ISSUE THREAD

**Issue by bingwer** [GDGincheonAndroidStudy/Seunghyo_B#1]
화면구성을 페이저별로
오늘날씨는 따로 보여주고
그 아래부분을 동일하게 리사이클러 뷰를 이용하여 3일치를 더 보여주고 싶은데
현재 저의 소스 코드 상태에서 페이저 안에 리사이클러뷰를 넣으려면
어떻게 해야 효과적일까요?

**Comment by yong076** [comment]
혹시 푸시 해주실수 있나요? 현제 소스에서는 Pager가 등록된게 아니라. 확인이 안되네요.

가장 좋은 방법은 MainActivity 초기화 할때 모든 데이터를 받아다가 Fragment가 변경 될때 마다 데이터를 뿌리는게 제일 좋은 방법 입니다.
[Data Class가 하나 필요 하겠죠?]

fragment_main.xml - 전체를 감싼 RelativeLayout안에 리사이클러뷰를 생성, 상단에는 오늘 날씨 표현할 ImageView & TextView 같은것을 선언 하고.

하단에는 Recyclerview.

초기화 하는 방법은.

``` java
public class PagerAdapter extends FragmentPager{
...
...

@Override
public Fragment getItem(int position){
return blahblahFragment.newInstance(position);
}
```

이런 형식으로 페이저 어뎁터가 해당 프래그먼트를 초기화 할때에 값을 넘겨주면 편합니다.

``` java
public class blahblahFragment extneds Fragment{

ArrayList<String> Weather = new ...
ArrayList<String> Day = new...



public static blahblahFragment newInstance(position){
Data data = new Data();

Weather = data.get(position).getweather;
Day = data.get(position).getday;
}
```

로 초기화 해주시면 한 프레그먼트 에서도 여러 데이터를 사용 할 수 있습니다.
- 그런데 제일 쉽고 빠른 방법은 각 위치마다 Fragment를 여러개 놓고 (똑같은 레이아웃에 이름만 다른) switch  /case 로 제어 하시면 됩니다.

**Comment by bingwer** [comment]
지금 페이저 안에 리사이클러뷰를 넣고 선택된 아이템마다 날씨가 업데이트 되게끔 해놓긴 했는데
제대로 했는지 잘 모르겠네요 한번 살펴봐 주시면 감사하겠습니다.
그리고 또 예전에 데이터를 받아올때 표시가 한글로 됬었는데 어느순간부터 영어로만 나오더라구요
다시 맑음/흐림 이런식으로 한글로 받아올 수 있는 방법이 있을까요?
